### ISSUE TITLE
Determine the best way to organize extensions in the README

### ISSUE THREAD

**Issue by kathrynkodama** [MicroShed/vscode-microprofile-pack#2]
See potential options below:

**Option A: All extensions listed at once**
<img width="793" alt="Screen Shot 2020-01-15 at 11 07 47 AM" src="https://user-images.githubusercontent.com/26146482/72815872-55e18e00-3c35-11ea-93b0-c2de0f24e4f6.png">

**Option B: Extensions divided into categories**
<img width="794" alt="Screen Shot 2020-01-15 at 11 09 35 AM" src="https://user-images.githubusercontent.com/26146482/72815873-567a2480-3c35-11ea-9d7b-e48d52a52c47.png">

**Comment by Emily-Jiang** [comment]
Option B looks good. The layout is self explainatory.

**Comment by cealsair** [comment]
Before I cast my vote, could you please include the actual URLs for all the links above? Thank you

**Comment by cealsair** [comment]
I prefer option B

**Comment by NottyCode** [comment]
I also prefer option B. It is clearer what is going on.

**Comment by rdebusscher** [comment]
Option B as there is better distinction between the 2 'types' of links

**Comment by cazucito** [comment]
Option B sounds better

**Comment by kathrynkodama** [comment]
Proceeding with Option B
